GuiControl, Disabled, FX
GuiControl, Disabled, FY
GuiControl, Disabled, SX
GuiControl, Disabled, SY
GuiControl, Disabled, Name
GuiControl, Disabled, Delay
GuiControl, Disabled, WA
GuiControl, Disabled, UI90
GuiControl, Disabled, SMP

GuiControl, Disabled, Alliance
GuiControl, Disabled, Corporation
GuiControl, Disabled, ExcellentStanding
GuiControl, Disabled, GoodStanding
GuiControl, Disabled, MilitiaAlly
GuiControl, Disabled, Fleet

GuiControl, Disabled, AvailableKillRight
GuiControl, Disabled, BadStanding
GuiControl, Disabled, Bounty
GuiControl, Disabled, Criminal
GuiControl, Disabled, LimitedEngagement
GuiControl, Disabled, MilitiaWar
GuiControl, Disabled, Neutral
GuiControl, Disabled, Outlaw
GuiControl, Disabled, SecurityStatusBelowZero
GuiControl, Disabled, Suspect
GuiControl, Disabled, TerribleStanding
GuiControl, Disabled, War

GuiControl, Disabled, Drone
GuiControl, Disabled, Sentry_drone
GuiControl, Disabled, Fighter
GuiControl, Disabled, Capsule
GuiControl, Disabled, Shuttle
GuiControl, Disabled, Rookie
GuiControl, Disabled, Mining_frigate
GuiControl, Disabled, Mining_barge
GuiControl, Disabled, Industrial
GuiControl, Disabled, Industrial_command
GuiControl, Disabled, Industrial_capital
GuiControl, Disabled, Sentry

GuiControl, Disabled, Frigate
GuiControl, Disabled, Destroyer
GuiControl, Disabled, Cruiser
GuiControl, Disabled, Battlecruiser
GuiControl, Disabled, Battleship
GuiControl, Disabled, Dreadnought
GuiControl, Disabled, Carrier
GuiControl, Disabled, Supercarrier
GuiControl, Disabled, Titan
